version: "3.9"  # optional since v1.27.0
services:
  user:
    build: ./users-api
    volumes:
      - ./users-api/src:/users-api/src
    ports:
      - "3000:3000"
  match:
    build: ./match-api
    volumes:
      - ./match-api/src:/match-api/src
    ports:
      - "3100:3100"
    depends_on:
      - user
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx:ro
    ports:
      - "8080:8080"
    depends_on:
      - user
      - match